# Generated by Django 4.0.4 on 2022-06-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('preview', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('views', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('uploadtime', models.CharField(max_length=20)),
            ],
        ),
    ]
