# Generated by Django 4.0.4 on 2022-06-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='videos',
            name='preview',
        ),
    ]
