# Generated by Django 4.0.4 on 2022-06-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_useraccount_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
