# Generated by Django 4.0.4 on 2022-06-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_videos_options_remove_videos_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={},
        ),
        migrations.AddField(
            model_name='videos',
            name='preview',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
