# Generated by Django 4.0.4 on 2022-06-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_videos_options_videos_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
