# Generated by Django 4.0.4 on 2022-06-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_useraccount_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videos',
            name='owner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
