# Generated by Django 4.0.4 on 2022-06-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_videos_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('nickname', models.CharField(max_length=255)),
                ('header', models.ImageField(null=True, upload_to='images/')),
                ('description', models.TextField(blank=True)),
                ('avatar', models.ImageField(null=True, upload_to='images/')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='videos',
            name='uploadtime',
        ),
        migrations.AddField(
            model_name='videos',
            name='length',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='owner_id',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default='2018-03-11'),
            preserve_default=False,
        ),
    ]
