# Generated by Django 4.0.4 on 2022-06-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_useraccount_account_id_alter_videos_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videos',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videos',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
