# Generated by Django 4.0.4 on 2022-06-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_useraccount_remove_videos_uploadtime_videos_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='owner_id',
            field=models.IntegerField(blank=True),
        ),
    ]
